# default configuration
default: &default
  weights_dir:  ./vit_weights/

# vit_base_patch16_224
vit_base_patch16_224:
  url: https://github.com/DanielHuang0105/vit_model_weight/releases/download/v1.0/vit_base_patch16_224_pytorch_model.bin
  <<: *default

# convit_base
convit_base:
  url: https://github.com/DanielHuang0105/vit_model_weight/releases/download/v1.0/convit_base_pytorch_model.bin
  <<: *default

# deit_base_distilled_patch16_224
deit_base_distilled_patch16_224:
  url: https://github.com/DanielHuang0105/vit_model_weight/releases/download/v1.0/deit_base_distilled_patch16_224_pytorch_model.bin
  <<: *default

# deit_base_patch16_224
levit_256:
  url: https://github.com/DanielHuang0105/vit_model_weight/releases/download/v1.0/levit_256_pytorch_model.bin
  <<: *default

# pit_b_224
pit_b_224:
  url: https://github.com/DanielHuang0105/vit_model_weight/releases/download/v1.0/pit_b_224_pytorch_model.bin
  <<: *default

# pit_s_224
swin_tiny_patch4_window7_224:
  url: https://github.com/DanielHuang0105/vit_model_weight/releases/download/v1.0/swin_tiny_patch4_window7_224_pytorch_model.bin
  <<: *default

# visformer_small
visformer_small:
  url: https://github.com/DanielHuang0105/vit_model_weight/releases/download/v1.0/visformer_small_pytorch_model.bin
  <<: *default

# cait_s24_224
cait_s24_224:
  url: https://github.com/DanielHuang0105/vit_model_weight/releases/download/v1.0/cait_s24_224_pytorch_model.bin
  <<: *default